### PR TITLE
rename solidus_extension_dev_tools -> solidus_dev_support

### PR DESCRIPTION
**Pull request by brchristian**

### CODE REVIEW

**Comment by brchristian** [comment]
I suspect this will resolve https://github.com/solidusio-contrib/solidus_handling_fees/issues/6

**Comment by aldesantis** [comment]
@brchristian thanks! You should also remove it from the Gemfile.

**Comment by brchristian** [comment]
@aldesantis Done. Now it looks like specs are failing because it can’t find `solidus_support`. Hmm. Any idea what that’s about?

**Comment by aldesantis** [comment]
@brchristian are you sure? The failures don't look related to solidus_support to me.

**Comment by brchristian** [comment]
@aldesantis Looks like specs are now passing.

**Pull request merged**
